from __future__ import annotations

import json
import math
import shutil
import subprocess
import tempfile
import wave
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "models" / "piper" / "ru_RU-denis-medium.onnx"
CONFIG = ROOT / "models" / "piper" / "ru_RU-denis-medium.onnx.json"
PIPER = Path(r"C:\Temp\piper-celeb-venv\Scripts\piper.exe")
OUT_DIR = ROOT / "assets" / "audio"
RAW = OUT_DIR / "voice-denis-raw.wav"
FINAL = OUT_DIR / "voice-denis.wav"

TEXT = (
    "Личные вещи Басты и Крида сегодня продают в Москве. "
    "Но деньги заберут не звёзды. "
    "Более двухсот артистов и блогеров передали свыше двух тысяч вещей. "
    "Среди лотов — часы Сергея Бурунова из сериала «Кибердеревня». "
    "И платье Екатерины Волковой с синей дорожки VK Fest. "
    "Все средства направят на социальные и экологические инициативы. "
    "За три года проект собрал больше четырёх с половиной миллионов рублей. "
    "Самый дорогой лот здесь — не имя, а помощь."
)

CAPTIONS = [
    "Личные вещи Басты и Крида",
    "сегодня продают в Москве",
    "Но деньги заберут не звёзды",
    "Более двухсот артистов и блогеров",
    "передали свыше двух тысяч вещей",
    "Среди лотов — часы Сергея Бурунова",
    "из сериала «Кибердеревня»",
    "И платье Екатерины Волковой",
    "с синей дорожки VK Fest",
    "Все средства направят",
    "на социальные и экологические инициативы",
    "За три года проект собрал",
    "больше четырёх с половиной миллионов",
    "Самый дорогой лот здесь",
    "не имя, а помощь",
]


def process_voice(src: Path, dst: Path) -> tuple[int, int, float]:
    with wave.open(str(src), "rb") as reader:
        channels = reader.getnchannels()
        sample_width = reader.getsampwidth()
        rate = reader.getframerate()
        frames = reader.readframes(reader.getnframes())
    if channels != 1 or sample_width != 2:
        raise RuntimeError(f"expected mono 16-bit WAV, got {channels=} {sample_width=}")

    x = np.frombuffer(frames, dtype=np.int16).astype(np.float64) / 32768.0
    # Voice-safe offline polish: remove low rumble, add a restrained presence shelf,
    # then use a soft-knee tanh compressor and normalize to -1 dBFS.
    alpha_hp = math.exp(-2.0 * math.pi * 70.0 / rate)
    hp = np.empty_like(x)
    hp[0] = x[0]
    for i in range(1, x.size):
        hp[i] = alpha_hp * (hp[i - 1] + x[i] - x[i - 1])

    alpha_lp = 1.0 - math.exp(-2.0 * math.pi * 2800.0 / rate)
    lp = np.empty_like(hp)
    lp[0] = hp[0]
    for i in range(1, hp.size):
        lp[i] = lp[i - 1] + alpha_lp * (hp[i] - lp[i - 1])
    present = hp + 0.10 * (hp - lp)
    compressed = np.tanh(present * 1.32) / np.tanh(1.32)
    peak = float(np.max(np.abs(compressed))) or 1.0
    polished = compressed * ((10.0 ** (-1.0 / 20.0)) / peak)
    pcm = np.clip(polished * 32767.0, -32768, 32767).astype(np.int16)

    with wave.open(str(dst), "wb") as writer:
        writer.setnchannels(1)
        writer.setsampwidth(2)
        writer.setframerate(rate)
        writer.writeframes(pcm.tobytes())
    duration = pcm.size / rate
    return rate, pcm.size, duration


def caption_manifest(duration: float) -> list[dict[str, object]]:
    weights = []
    for index, text in enumerate(CAPTIONS):
        weight = len(text.replace("—", " ").split())
        if index in {1, 2, 4, 6, 8, 10, 12, 14}:
            weight += 0.55
        weights.append(weight)
    usable = max(0.0, duration - 0.10)
    unit = usable / sum(weights)
    cursor = 0.05
    result = []
    for index, (text, weight) in enumerate(zip(CAPTIONS, weights), start=1):
        seg_duration = weight * unit
        result.append(
            {
                "id": f"caption-{index:02d}",
                "text": text,
                "start": round(cursor, 3),
                "duration": round(seg_duration, 3),
            }
        )
        cursor += seg_duration
    return result


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # piper's Windows espeak bridge cannot resolve a Cyrillic data path reliably.
    # Stage inference under an ASCII-only temporary directory, then copy the
    # generated bytes back into the self-contained project.
    stage = Path(tempfile.gettempdir()) / "piper-celeb-denis"
    stage.mkdir(parents=True, exist_ok=True)
    stage_model = stage / MODEL.name
    stage_config = stage / CONFIG.name
    stage_raw = stage / RAW.name
    stage_text = stage / "voice.txt"
    shutil.copy2(MODEL, stage_model)
    shutil.copy2(CONFIG, stage_config)
    stage_text.write_text(TEXT + "\n", encoding="utf-8")
    subprocess.run(
        [
            str(PIPER),
            "--model",
            str(stage_model),
            "--config",
            str(stage_config),
            "--input-file",
            str(stage_text),
            "--output-file",
            str(stage_raw),
            "--length-scale",
            "0.95",
            "--noise-scale",
            "0.55",
            "--noise-w-scale",
            "0.72",
            "--sentence-silence",
            "0.16",
        ],
        check=True,
    )
    shutil.copy2(stage_raw, RAW)
    rate, samples, duration = process_voice(RAW, FINAL)
    manifest = {
        "provider": "piper",
        "voice": "ru_RU-denis-medium",
        "dataset_license": "CC0",
        "model_card": "https://huggingface.co/rhasspy/piper-voices/blob/main/ru/ru_RU/denis/medium/MODEL_CARD",
        "sample_rate": rate,
        "samples": samples,
        "duration": round(duration, 3),
        "captions": caption_manifest(duration),
    }
    (OUT_DIR / "voice_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps({"duration": round(duration, 3), "output": str(FINAL)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
